target = "compliance/framework/aws-kms/aws-kms-key-arn.txt#2.9"

# 2.9.  Identifying an an AWS KMS multi-Region identifier
#
# This function MUST take a single AWS KMS identifier
# 
# If the input starts with "arn:", this MUST return the output of
# identifying an an AWS KMS multi-Region ARN (aws-kms-key-
# arn.md#identifying-an-an-aws-kms-multi-region-arn) called with this
# input.  If the input starts with "alias/", this an AWS KMS alias and
# not a multi-Region key id and MUST return false.  If the input starts
# with "mrk-", this is a multi-Region key id and MUST return true.  If
# the input does not start with any of the above, this is not a multi-
# Region key id and MUST return false.

[[spec]]
level = "MUST"
quote = '''
This function MUST take a single AWS KMS identifier
'''

[[spec]]
level = "MUST"
quote = '''
If the input starts with "arn:", this MUST return the output of
identifying an an AWS KMS multi-Region ARN (aws-kms-key-
arn.md#identifying-an-an-aws-kms-multi-region-arn) called with this
input.
'''

[[spec]]
level = "MUST"
quote = '''
If the input starts with "alias/", this an AWS KMS alias and
not a multi-Region key id and MUST return false.
'''

[[spec]]
level = "MUST"
quote = '''
If the input starts
with "mrk-", this is a multi-Region key id and MUST return true.
'''

[[spec]]
level = "MUST"
quote = '''
If
the input does not start with any of the above, this is not a multi-
Region key id and MUST return false.
'''

